/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:8e7dab6d-19b6-44ef-ae36-b98c88b796d5",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_zNMwdPDae",
    "aws_user_pools_web_client_id": "m233i9p9djrdpttdr0mb677ul",
    "oauth": {}
};


export default awsmobile;
